# Generated by Django 5.1.4 on 2024-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Default Name', max_length=20),
        ),
    ]
