# Generated by Django 5.1.4 on 2024-12-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0007_remove_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
